### DISCUSSION TITLE
What are the system that you are targeting?

### DISCUSSION THREAD

**Discussion by benyaminl** [dxdotdev/arc-ui#13] [General]
Hello @dreisss 
Thank you for creating such great userChrome! I really being helped by this css

But I'm curious, by any chance, what system you tested with, and is it works as the screenshoot on the readme? 

Because I tried to install and I need to tweak here and there (even on stable firefox, I'm on 129 Firefox Fedora Workstation 40). 

And it's tedious as the bookmark is broken, plus the tab bar is a mess (in the end I fix it, but well.. I want to know if it's only happen on my screen, as I have 1920x1080, I seen manythings already use percentage, but well.. it doesn't works out of the box).

 Thank you

**Comment by dreisss** [comment]
Thanks to your feedback @benyaminl, I was expecting feedbacks like this when shared the theme

But, yes, it works exactly like the screenshot in my computer. I found some bugs and I'll fix it, but the main features are working correctly to me

You can create issues or tell me the bugs you found or fixes you did, so I can fix them

And this is the system I tested:

![image](https://github.com/user-attachments/assets/0100a3e9-446b-41da-8fcb-5b142b3d1724)

And Mozilla Firefox (129.0.2)

**Reply by benyaminl** [reply]
To be honest, I did a lot of fixes. I need to do diff file on the css file. 

Let be get back fast. 

EDIT : 

My System detail could be looked 

![image](https://github.com/user-attachments/assets/ee763a38-60ec-4da1-a79f-7919efe1a8b3)

Seems wer have same theme, orchis which make it simpler to test (I hope this isn't a problem because of gtk theme)

2nd thing is I set my toolbar to be be compact on firefox. But fresh normal density, it result of the same problem. 
Dunno why

**Reply by benyaminl** [reply]
Problem that I found is when using fresh userChrome.css with new profiles, I got 

![image](https://github.com/user-attachments/assets/4349c7c6-f56a-4cf8-a76e-22d58e171eb6)

To Be Fixed I need to change
```css

.titlebar-button {
    padding: .25rem !important;
    position: fixed;
    left: 0;
   /* the rest are same */
}

/* Several change, can be seen on vs code diff screenshoot */
#tabbrowser-arrowscrollbox {
    --tabs-top-padding: 0px;
    max-height: calc(100vh - var(--browser-padding) - 5*var(--sidebar-padding) - 2rem - 3.5rem - 2.5rem);
    position: absolute;
    right: 0rem;
    height: calc(100vh - var(--browser-padding) - 5*var(--sidebar-padding) - 3.5rem - 4.5rem);
    /*! top: calc(3.5rem + 2*var(--sidebar-padding)) !important; */
    width: calc(var(--sidebar-width) - 1rem) !important;
    padding-top: calc(1.5rem + 2.5rem + 3*var(--sidebar-padding) + var(--tabs-top-padding)) !important;


    & .tabbrowser-tab {
        width: 100% !important;
        max-width: none !important;
        max-height: 2.2rem !important;
        padding: 0 !important;
        

        &:hover .tab-background:not([selected]) {
            background-color: var(--color-stroke) !important
        }

        &:not([fadein]) {
            display: none
        }
    }

    & .tab-background {
        transition: background-color .1s ease-in-out;
        border-radius: 5px !important;
        outline: none !important;
        margin: 0 !important;

        &[selected] {
            box-shadow: none !important;
            background-color: var(--color-surface-highlight) !important;
            opacity: 0.8;
            padding: 0 0.5rem;
        }
    }

    & .tab-content {
        padding: 0 0.2rem !important
    }

    & .tab-icon-image {
        margin-right: .6rem !important
    }

    & .tab-close-button {
        border-radius: 100% !important
    }
}
```

![image](https://github.com/user-attachments/assets/fed979e3-48e8-451e-99a8-e4c57742dd52)

The Diff Code based on the css release file
![image](https://github.com/user-attachments/assets/983f296f-9e1b-4870-930b-edb8fad2e5aa)
